-
  hosts: localhost
  vars:
          service_name: nginx
          project_root: /var/www/html
          file_name: index.html
  tasks: 
    - name: Install nginx server
      yum: pkg={{ service_name }} 
    - name: Enable Apache on systemd
      service: name={{ service_name }} enabled=yes
      notify: restart apache
    - name: restart apache
      service: name={{ service_name }} state=restarted
