---
 - name: sampleplaybook
   hosts: all
   become: yes
   become_user: root
   tasks: 
        - name: ensure latest version apache
          yum:
                  name: httpd
                  state: latest
        - name: ensure running apache
          service: 
                  name : httpd
                  state: started
