---
- name: configure webapp
  hosts: groupA
  vars: 
    repo: myrepo.com/repo.git
    version: 8

  tasks: 
    - name: install nginx
      debug:
        msg: "dnf install nginx"

    - name: ensure web directory
      debug:
        msg: "mkdir /webapp"
    - name: get content
      debug:
        msg: "git clone --branch {{ version }} {{ repo }} /webapp"
    - name: nginx config
      debug:
        msg: "put nginx config in place"
      notify: restart nginx service
      changed_when: True

    - name: ensure nginx running
      debug:
        msg: "service start nginx"

  handlers:
    - name: restart nginx service
      debug:
        msg: "systemctl restart nginx"
